-- Fase 0: baseline migration. PostGIS nao e usado por nenhuma entidade do NimbusNovax
-- (era codigo herdado do clone do NimbusFlow) - extensao removida para nao depender de
-- um Postgres com PostGIS instalado (o Postgres gerenciado do Railway nao tem).
